x-chatbot-app: &chatbot-app
  image: chatbot-app
  build:
    dockerfile: ./apps/chatbot/Dockerfile
  env_file:
    - .env
  environment:
    - NODE_ENV=production
    - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
    - CHROMA_HOST=chromadb
    - OLLAMA_BASE_URL=http://ollama:11434
    - RABBITMQ_URL=amqp://rabbitmq
    - STORAGE_DIR=/app/uploads
  volumes:
    - uploads:/app/uploads
  tty: true
  restart: on-failure
  depends_on:
    chromadb:
      condition: service_healthy
    ollama:
      condition: service_healthy
    rabbitmq:
      condition: service_healthy
    otel-collector:
      condition: service_started

services:
  chromadb:
    image: chromadb/chroma
    ports:
      - '8000:8000'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "bash -c 'exec 3<>/dev/tcp/127.0.0.1/8000 && echo -e \"GET /api/v2/heartbeat HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n\" >&3 && cat <&3 | grep \"200 OK\"'",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  rabbitmq:
    image: rabbitmq:4.2.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_ERLANG_COOKIE=a_very_long_secret_cookie_for_rabbitmq_4_0
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  ollama:
    build:
      dockerfile: ollama.Dockerfile
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:11434/api/tags']
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s

  app1:
    <<: *chatbot-app

  app2:
    <<: *chatbot-app

  worker:
    <<: *chatbot-app
    image: vector-db-worker
    build:
      dockerfile: ./apps/vector-db-worker/Dockerfile
    env_file:
      - .env

  nginx:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - '8080:80'
    environment:
      - SERVER_1=app1
      - SERVER_2=app2
    depends_on:
      - app1
      - app2

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
      - 12345:12345 # Prometheus metrics exposed by the app itself

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  ollama_data:
  uploads:
