receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

connectors:
  spanmetrics:
    namespace: langchain_chatbot
    dimensions:
      - name: http.method
      - name: http.url
      - name: http.status_code
      - name: http.route
    exclude_dimensions: ['status.code']

processors:
  transform/span:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(span.attributes["http.url"], span.attributes["http.route"])
          - delete_key(span.attributes, "http.route")

exporters:
  debug:
    verbosity: detailed
  zipkin/nontls:
    endpoint: 'http://zipkin:9411/api/v2/spans'
    format: proto
  prometheus:
    endpoint: 0.0.0.0:12345

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform/span]
      exporters: [debug, zipkin/nontls, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      exporters: [debug]
